### PR TITLE
add azure storage support

### PR DESCRIPTION
**Pull request by neallclark**
Adds support for uploading/downloading backups to or from Azure Storage.
It adds 2 new environment variables to configure this.
`AZURE_STORAGE_CONTAINER_NAME` - Name of container to store the backup in
`AZURE_STORAGE_CONNECTION_STRING` - Connection string

#126

### CODE REVIEW

**Comment by acjohnson** [comment]
Thanks for the contrib @neallclark :+1: for merge!

**Comment by ysde** [comment]
Hi @neallclark thanks!

Can you help add the example setting to the [grafan-backup.example.json](https://github.com/ysde/grafana-backup-tool/blob/65ec52402d6f61011bd18d8e57a7b809c512c204/examples/grafana-backup.example.json)

By the way, does Azure need any secret keys or credentials to upload file to or download file from ?

Thank you!

**Comment by acjohnson** [comment]
Creds should be in the connection string https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/storage/common/storage-configure-connection-string.md#configure-a-connection-string-for-an-azure-storage-account

**Comment by neallclark** [comment]
I've updated the grafana-backup.example.json file.

For the connection settings, I just followed this guide for their python SDK https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python
It looks like you can split the account URL and the token into 2 settings, which could be added at a later date if needed https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python

**Pull request merged**
