### PR TITLE
Added the ability to use multiple hard-coded settings

### PR DESCRIPTION
**Pull request by Mikey1993**
1) Added the ability to use multiple hard-coded settings files in `src/conf/` directory.
2) Changed import statements to reflect better what is used in which file - don't use `from x import *`, but instead specify the functions that are needed to be imported.
3) Fixed a typo.
4) Reformatted the code.
5) Updated README.

### CODE REVIEW

**Comment by Mikey1993** [comment]
@ysde , I have pushed a change so that the code can be compatible with python 2 too.
What do you think?

**Comment by Mikey1993** [comment]
@ysde , Some more fixes.

**Comment by ysde** [comment]
Hi @Mikey1993 

Thanks for the help.

Is this version compatible with `Python 2 .x` ?

Thank you

**Comment by Mikey1993** [comment]
> 
> 
> Hi @Mikey1993
> 
> Thanks for the help.
> 
> Is this version compatible with `Python 2 .x` ?
> 
> Thank you

@ysde ,
I think it should be compatible, but I haven't been able to test it on `Python 2.x`.
I haven't introduced any `Python 3.x` specific code as far as I know.

**Pull request merged**
