### PR TITLE
Make GRAFANA_HEADERS environment optional

### PR DESCRIPTION
**Pull request by brandon-vargas**
The current solution does not allow the GRAFANA_HEADERS to be optional. Pulling the if statement outside the dictionary comprehension to allow the variable to be optional.

### CODE REVIEW

**Comment by ysde** [comment]
@brandon-vargas thank you for finding the problem.

**Comment by xmj** [comment]
this works,

you could probably also do
```
EXTRA_HEADERS = dict(h.split(':') for h in os.getenv('GRAFANA_HEADERS', '').split(','))
```

instead of the if clause

so that `os.getenv` returns an empty string

**Comment by brandon-vargas** [comment]
> this works,
> 
> you could probably also do
> 
> ```
> EXTRA_HEADERS = dict(h.split(':') for h in os.getenv('GRAFANA_HEADERS', '').split(','))
> ```
> 
> instead of the if clause
> 
> so that `os.getenv` returns an empty string

In respect to @xmj comment, i tested their recommendation and i get an error. 
This is the error:
```
  File "grafanaSettings.py", line 6, in <module>
    EXTRA_HEADERS = dict(h.split(':') for h in os.getenv('GRAFANA_HEADERS', '').split(','))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
But building off the recommendation, the below proposition is tested and works. 
```
EXTRA_HEADERS = dict(h.split(':') for h in os.getenv('GRAFANA_HEADERS', '').split(',') if 'GRAFANA_HEADERS' in os.environ)
```

**Comment by xmj** [comment]
thanks!

**Pull request merged**
