### PR TITLE
fix(log): change json decoding

### PR DESCRIPTION
**Pull request by azman0101**
Fix decoding error

```

########################################

[DEBUG] resp status: 200
Traceback (most recent call last):
  File "/usr/bin/grafana-backup", line 11, in <module>
    load_entry_point('grafana-backup==1.1.6', 'console_scripts', 'grafana-backup')()
  File "/usr/lib/python3.8/site-packages/grafana_backup/cli.py", line 43, in main
    save(args, settings)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save.py", line 43, in main
    backup_functions[backup_function](args, settings)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save_folders.py", line 26, in main
    get_individual_folder_setting_and_save(folders, folder_path, log_file, grafana_url, http_get_headers, verify_ssl, client_cert, debug, pretty_print, uid_support)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save_folders.py", line 59, in get_individual_folder_setting_and_save
    (status, content) = get_folder(folder_uri, grafana_url, http_get_headers, verify_ssl, client_cert, debug)
  File "/usr/lib/python3.8/site-packages/grafana_backup/dashboardApi.py", line 120, in get_folder
    (status_code, content) = send_grafana_get('{0}/api/folders/{1}'.format(grafana_url, uid), http_get_headers,
  File "/usr/lib/python3.8/site-packages/grafana_backup/dashboardApi.py", line 186, in send_grafana_get
    log_response(r)
  File "/usr/lib/python3.8/site-packages/grafana_backup/commons.py", line 13, in log_response
    print("[DEBUG] resp body: {0}".format(resp.json()))
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### CODE REVIEW

**Comment by azman0101** [comment]
I have another error:

```


        window.onload = function() {
          var preloader = document.getElementsByClassName("preloader");
          if (preloader.length) {
            preloader[0].className = "preloader preloader--done";
          }
        };
    </script>




    <script src="public/build/runtime.77c6cb2b767d3da10797.js" type="text/javascript"></script>
    <script src="public/build/angular~app.77c6cb2b767d3da10797.js" type="text/javascript"></script>
    <script src="public/build/app.77c6cb2b767d3da10797.js" type="text/javascript"></script>
    <script src="public/build/moment~app.77c6cb2b767d3da10797.js" type="text/javascript"></script>
    <script src="public/build/vendors~app.77c6cb2b767d3da10797.js" type="text/javascript"></script>
    <script>
      performance.mark('js done blocking');
    </script>
  </body>
</html>

Traceback (most recent call last):
  File "/usr/bin/grafana-backup", line 11, in <module>
    load_entry_point('grafana-backup==1.1.6', 'console_scripts', 'grafana-backup')()
  File "/usr/lib/python3.8/site-packages/grafana_backup/cli.py", line 43, in main
    save(args, settings)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save.py", line 43, in main
    backup_functions[backup_function](args, settings)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save_folders.py", line 26, in main
    get_individual_folder_setting_and_save(folders, folder_path, log_file, grafana_url, http_get_headers, verify_ssl, client_cert, debug, pretty_print, uid_support)
  File "/usr/lib/python3.8/site-packages/grafana_backup/save_folders.py", line 59, in get_individual_folder_setting_and_save
    (status, content) = get_folder(folder_uri, grafana_url, http_get_headers, verify_ssl, client_cert, debug)
  File "/usr/lib/python3.8/site-packages/grafana_backup/dashboardApi.py", line 120, in get_folder
    (status_code, content) = send_grafana_get('{0}/api/folders/{1}'.format(grafana_url, uid), http_get_headers,
  File "/usr/lib/python3.8/site-packages/grafana_backup/dashboardApi.py", line 187, in send_grafana_get
    return (r.status_code, r.json())
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by acjohnson** [comment]
These are probably all OK changes to make but aren't fixing the actual problem @azman0101 @ysde

We need to get #123 merged asap as this fixes the bug that I introduced in my last pr... apologies

**Comment by acjohnson** [comment]
We need to get #124 merged asap as this fixes the bug that I introduced in my last pr... apologies

**Comment by azman0101** [comment]
I'm closing this issue, as @acjohnson has pointed it out #124 fixed the bug.

**Pull request closed without merging**
