### PR TITLE
Add folder permissions backup

### PR DESCRIPTION
**Pull request by jartigag**
I wrote the `get_folder_permissions` and `update_folder_permissions` functions, and everything else to make the tool work with the Grafana Permissions API (also fix the ["organaizations"](https://github.com/ysde/grafana-backup-tool/commit/c70407507599b7f2a27a69826c5d7ed494cb5fad) typo).

I started from the fork commented in #90, so now I see `restore.py` may have diverged, specially in that [`restore_from_dir`](https://github.com/ysde/grafana-backup-tool/blob/4bdf220a0d8faa3ac0c5c0a1261c297be7917e18/grafana_backup/restore.py#L123) function.

¿How should I proceed?

### CODE REVIEW

**Comment by acjohnson** [comment]
@jartigag can you rebase against `master` and ensure it works properly there? Why is the fork mentioned in #90 important to the folder permissions changes you are proposing?

**Comment by jartigag** [comment]
I'll try the rebase against master.

The fork isn't relevant to the folder permissions changes, but I started from there and I saw that difference in `restore.py` when i opened this PR.

Let's see if I manage to make it right.

**Comment by acjohnson** [comment]
@jartigag let's give this one more re-base against `master` and we should be able to get it merged

**Comment by jartigag** [comment]
Why it is unused?

**Comment by acjohnson** [comment]
Good question @jartigag you wrote it lol... If you aren't sure why it is there then I'll assume it was a mistake and delete. Thanks!

**Comment by acjohnson** [comment]
af51467038f83fbabf2847bbc75abf4d9a90fbbd solves this and the `restore_from_dir` function is now deleted

**Pull request merged**
