### PR TITLE
Add alert rules to backup

### PR DESCRIPTION
**Pull request by mt3593**
Back up of alert_rules, addresses #197 

I am by no means a python developer, so please let me know what i've got wrong

### CODE REVIEW

**Comment by mt3593** [comment]
I've tested this locally and was able to copy alert rules from one grafana to the other.

**Comment by acjohnson** [comment]
Mind adding `alert_rules` to the list of components in the docopt cli? I know this line is getting long and at some point we'll want to find a better way to format it... but... for now it should at least list all supported components IMHO.
https://github.com/ysde/grafana-backup-tool/blob/master/grafana_backup/cli.py#L28

**Comment by acjohnson** [comment]
Thank you for your contribution @mt3593 !

**Comment by mt3593** [comment]
@acjohnson Thanks for that.  When is the next version due for release?

**Comment by mt3593** [comment]
> @acjohnson Thanks for that. When is the next version due for release?

sorry to pester @acjohnson, keen to get the updated version :)

**Comment by acjohnson** [comment]
@ysde The draft 1.2.6 release looks good to me if you want to publish it and get this out the door :grin:

**Comment by michyliao** [comment]
Hey! Just wanted to mention that this merge should have a break change notice - to be up to date with the latest grafana version. We're still using `8.2.4` and our backup job failed with a 404 on `alert-rules`.

**Comment by acjohnson** [comment]
@michyliao thank you for the heads up in that case it'd be better if we can add a version check for `alert-rules` support rather than adding a break change.

**Pull request merged**
