### PR TITLE
fix KeyError: 'folderUid' while restoring

### PR DESCRIPTION
**Pull request by israelshenkar**

### CODE REVIEW

**Comment by israelshenkar** [comment]
@ysde

**Comment by israelshenkar** [comment]
https://github.com/ysde/grafana-backup-tool/issues/178

**Comment by ysde** [comment]
Hi @israelshenkar 
I think this PR might not be an appropriate change.

https://grafana.com/docs/grafana/v8.2/http_api/dashboard/
it needs either `folderUid` or `folderId` , maybe in your case, you don't have `folderUid` when you export your `grafana`.

**Comment by israelshenkar** [comment]
Hi @ysde
i was exporting grafana in version 7....

**Comment by acjohnson** [comment]
@israelshenkar could you please share your specific Grafana version and perhaps full stack trace of when you received this error? Thanks!

**Pull request closed without merging**
